
#spring.application.name=newsfeed19

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true
        page-parameter: pageNumber
        size-parameter: pageSize

  jpa:
    hibernate:
      ddl-auto: update # or create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': DEBUG